### ISSUE TITLE
error with PyQt5

### ISSUE THREAD

**Issue by mikeygg-lab** [ZxnoGit/Deepwoken-AI-Fishing-Bot#1]
i have pyqt5 installed, but still says no module found with PyQt5
![image](https://github.com/user-attachments/assets/e5557c2f-15a2-43bd-ba05-7dd30d4857f9)

**Comment by ZxnoGit** [comment]
Hi, this might be a python version mismatch. it looks like you have the package installed on Python 3.11 and when you are typing py fishbot.py you might not be using the same python version you installed the package on. Try and type "py" in the cmd prompt and check if it runs the 3.11 python version
