### ISSUE TITLE
Stuck callibrating

### ISSUE THREAD

**Issue by mothmaildelivery** [ZxnoGit/Deepwoken-AI-Fishing-Bot#3]
Hello! My friend and I were able to get the program to run, but we are having an issue with it callibrating. We see the purple box appear and it throws the line out, but we don't see it doing anything after. I confirmed the box is big enough to catch the letters. Just nothing happens and it stays purple

**Comment by ZxnoGit** [comment]
hm are you letting all of the letters show up? the program needs to capture each one popping up to save the coords

**Comment by ZxnoGit** [comment]
you might need to throw a couple lines out to get it
